// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Smart_Gadget

#include "../ui.h"

void ui_Call_screen_init(void)
{
    ui_Call = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Call, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Call, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Call, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Call, &ui_img_pattern_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_Call, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Elena = ui_Small_Label_create(ui_Call);
    lv_obj_set_x(ui_Elena, 0);
    lv_obj_set_y(ui_Elena, 0);
    lv_obj_set_align(ui_Elena, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Elena, "Elena Smith Bergman");
    lv_obj_set_style_text_color(ui_Elena, lv_color_hex(0x000746), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Elena, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Incoming = ui_Small_Label_create(ui_Call);
    lv_obj_set_x(ui_Incoming, 0);
    lv_obj_set_y(ui_Incoming, 25);
    lv_obj_set_align(ui_Incoming, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Incoming, "Incoming Call");
    lv_obj_set_style_text_color(ui_Incoming, lv_color_hex(0x9C9CD9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Incoming, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Call_Incon1 = lv_obj_create(ui_Call);
    lv_obj_set_width(ui_Call_Incon1, 60);
    lv_obj_set_height(ui_Call_Incon1, 60);
    lv_obj_set_x(ui_Call_Incon1, -50);
    lv_obj_set_y(ui_Call_Incon1, -42);
    lv_obj_set_align(ui_Call_Incon1, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Call_Incon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Call_Incon1, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Call_Incon1, lv_color_hex(0xE63431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Call_Incon1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Call_Incon1, lv_color_hex(0xE63431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Call_Incon1, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Call_Incon1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Call_Incon1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Call_Incon1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Call_Incon1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Call_Incon1, lv_color_hex(0xFF5855), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Call_Incon1, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Phone1 = lv_img_create(ui_Call_Incon1);
    lv_img_set_src(ui_Phone1, &ui_img_phone_png);
    lv_obj_set_width(ui_Phone1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Phone1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Phone1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Phone1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Phone1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Phone1, 1360);

    ui_Call_Incon2 = lv_obj_create(ui_Call);
    lv_obj_set_width(ui_Call_Incon2, 60);
    lv_obj_set_height(ui_Call_Incon2, 60);
    lv_obj_set_x(ui_Call_Incon2, 50);
    lv_obj_set_y(ui_Call_Incon2, -42);
    lv_obj_set_align(ui_Call_Incon2, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Call_Incon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Call_Incon2, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Call_Incon2, lv_color_hex(0x10D262), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Call_Incon2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Call_Incon2, lv_color_hex(0x10D262), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Call_Incon2, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Call_Incon2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Call_Incon2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Call_Incon2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Call_Incon2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Call_Incon2, lv_color_hex(0x31EF81), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Call_Incon2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Phone2 = lv_img_create(ui_Call_Incon2);
    lv_img_set_src(ui_Phone2, &ui_img_phone_png);
    lv_obj_set_width(ui_Phone2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Phone2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Phone2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Phone2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Phone2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Scrolldots1 = ui_Scrolldots_create(ui_Call);
    lv_obj_set_x(ui_Scrolldots1, 0);
    lv_obj_set_y(ui_Scrolldots1, -8);

    lv_obj_set_width(ui_comp_get_child(ui_Scrolldots1, UI_COMP_SCROLLDOTS_D1), 4);
    lv_obj_set_height(ui_comp_get_child(ui_Scrolldots1, UI_COMP_SCROLLDOTS_D1), 4);

    lv_obj_set_width(ui_comp_get_child(ui_Scrolldots1, UI_COMP_SCROLLDOTS_D2), 8);
    lv_obj_set_height(ui_comp_get_child(ui_Scrolldots1, UI_COMP_SCROLLDOTS_D2), 8);
    lv_obj_set_x(ui_comp_get_child(ui_Scrolldots1, UI_COMP_SCROLLDOTS_D2), 11);
    lv_obj_set_y(ui_comp_get_child(ui_Scrolldots1, UI_COMP_SCROLLDOTS_D2), 0);
    lv_obj_set_style_bg_color(ui_comp_get_child(ui_Scrolldots1, UI_COMP_SCROLLDOTS_D2), lv_color_hex(0x101C52),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_comp_get_child(ui_Scrolldots1, UI_COMP_SCROLLDOTS_D2), 255, LV_PART_MAIN | LV_STATE_DEFAULT);







    lv_obj_add_event_cb(ui_Call, ui_event_Call, LV_EVENT_ALL, NULL);

}
