// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ee351_ui

#include "../ui.h"

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Home, &ui_img_bkg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Test = lv_img_create(ui_Home);
    lv_img_set_src(ui_BTN_Test, &ui_img_btn_print_down_png);
    lv_obj_set_width(ui_BTN_Test, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_BTN_Test, LV_SIZE_CONTENT);    /// 132
    lv_obj_set_x(ui_BTN_Test, -66);
    lv_obj_set_y(ui_BTN_Test, 25);
    lv_obj_set_align(ui_BTN_Test, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTN_Test, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTN_Test, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BTN_Test, 128);

    ui_Test_Top = lv_img_create(ui_BTN_Test);
    lv_img_set_src(ui_Test_Top, &ui_img_btn_print_top_off_png);
    lv_obj_set_width(ui_Test_Top, LV_SIZE_CONTENT);   /// 105
    lv_obj_set_height(ui_Test_Top, LV_SIZE_CONTENT);    /// 94
    lv_obj_set_align(ui_Test_Top, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Test_Top, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_img_set_zoom(ui_Test_Top, 128);
    lv_obj_set_style_radius(ui_Test_Top, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Test_Top, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Test_Top, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Test_Top, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Test_Top, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor(ui_Test_Top, lv_color_hex(0x67799B), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_Test_Top, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Test_Top_Icon = lv_img_create(ui_Test_Top);
    lv_img_set_src(ui_Test_Top_Icon, &ui_img_icn_stop_png);
    lv_obj_set_width(ui_Test_Top_Icon, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_Test_Top_Icon, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_align(ui_Test_Top_Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Test_Top_Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Test_Top_Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Test_Top_Icon, 128);

}
