// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ee351_ui

#include "../ui.h"

void ui_Light_screen_init(void)
{
    ui_Light = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Light, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Light, &ui_img_bkg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Light_Header = lv_obj_create(ui_Light);
    lv_obj_set_width(ui_Light_Header, 291);
    lv_obj_set_height(ui_Light_Header, 40);
    lv_obj_set_x(ui_Light_Header, 0);
    lv_obj_set_y(ui_Light_Header, -20);
    lv_obj_set_align(ui_Light_Header, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Light_Header, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Light_Header, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Light_Header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Light_Header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Light_Header, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Light_Header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Light_Header, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Light_Header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Light_Header_Label = lv_label_create(ui_Light_Header);
    lv_obj_set_width(ui_Light_Header_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Light_Header_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Light_Header_Label, 0);
    lv_obj_set_y(ui_Light_Header_Label, 10);
    lv_obj_set_align(ui_Light_Header_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Light_Header_Label, "Light Controller");
    lv_obj_set_style_text_color(ui_Light_Header_Label, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Light_Header_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Light_Header_Label, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Movexy = lv_img_create(ui_Light);
    lv_img_set_src(ui_BTN_Movexy, &ui_img_btn_pad_bottom_png);
    lv_obj_set_width(ui_BTN_Movexy, LV_SIZE_CONTENT);   /// 311
    lv_obj_set_height(ui_BTN_Movexy, LV_SIZE_CONTENT);    /// 311
    lv_obj_set_x(ui_BTN_Movexy, 64);
    lv_obj_set_y(ui_BTN_Movexy, 11);
    lv_obj_set_align(ui_BTN_Movexy, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTN_Movexy, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTN_Movexy, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BTN_Movexy, 128);

    ui_BTN_Movexy_Glow_Up = lv_obj_create(ui_BTN_Movexy);
    lv_obj_set_width(ui_BTN_Movexy_Glow_Up, 60);
    lv_obj_set_height(ui_BTN_Movexy_Glow_Up, 50);
    lv_obj_set_x(ui_BTN_Movexy_Glow_Up, 0);
    lv_obj_set_y(ui_BTN_Movexy_Glow_Up, -30);
    lv_obj_set_align(ui_BTN_Movexy_Glow_Up, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BTN_Movexy_Glow_Up, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BTN_Movexy_Glow_Up, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BTN_Movexy_Glow_Up, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTN_Movexy_Glow_Up, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_BTN_Movexy_Glow_Up, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_BTN_Movexy_Glow_Up, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BTN_Movexy_Glow_Up, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BTN_Movexy_Glow_Up, lv_color_hex(0x60BEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BTN_Movexy_Glow_Up, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BTN_Movexy_Glow_Up, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BTN_Movexy_Glow_Up, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_BTN_Movexy_Glow_Up, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_BTN_Movexy_Glow_Up, -5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_BTN_Movexy_Glow_Up, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Movexy_Glow_Down = lv_obj_create(ui_BTN_Movexy);
    lv_obj_set_width(ui_BTN_Movexy_Glow_Down, 60);
    lv_obj_set_height(ui_BTN_Movexy_Glow_Down, 50);
    lv_obj_set_x(ui_BTN_Movexy_Glow_Down, 0);
    lv_obj_set_y(ui_BTN_Movexy_Glow_Down, 30);
    lv_obj_set_align(ui_BTN_Movexy_Glow_Down, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BTN_Movexy_Glow_Down, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BTN_Movexy_Glow_Down, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BTN_Movexy_Glow_Down, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTN_Movexy_Glow_Down, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_BTN_Movexy_Glow_Down, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_BTN_Movexy_Glow_Down, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BTN_Movexy_Glow_Down, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BTN_Movexy_Glow_Down, lv_color_hex(0x60BEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BTN_Movexy_Glow_Down, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BTN_Movexy_Glow_Down, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BTN_Movexy_Glow_Down, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_BTN_Movexy_Glow_Down, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_BTN_Movexy_Glow_Down, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_BTN_Movexy_Glow_Down, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Movexy_Glow_Left = lv_obj_create(ui_BTN_Movexy);
    lv_obj_set_width(ui_BTN_Movexy_Glow_Left, 50);
    lv_obj_set_height(ui_BTN_Movexy_Glow_Left, 60);
    lv_obj_set_x(ui_BTN_Movexy_Glow_Left, -30);
    lv_obj_set_y(ui_BTN_Movexy_Glow_Left, 0);
    lv_obj_set_align(ui_BTN_Movexy_Glow_Left, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BTN_Movexy_Glow_Left, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BTN_Movexy_Glow_Left, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BTN_Movexy_Glow_Left, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTN_Movexy_Glow_Left, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_BTN_Movexy_Glow_Left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_BTN_Movexy_Glow_Left, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BTN_Movexy_Glow_Left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BTN_Movexy_Glow_Left, lv_color_hex(0x60BEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BTN_Movexy_Glow_Left, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BTN_Movexy_Glow_Left, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BTN_Movexy_Glow_Left, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_BTN_Movexy_Glow_Left, -5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_BTN_Movexy_Glow_Left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_BTN_Movexy_Glow_Left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Movexy_Glow_Right = lv_obj_create(ui_BTN_Movexy);
    lv_obj_set_width(ui_BTN_Movexy_Glow_Right, 50);
    lv_obj_set_height(ui_BTN_Movexy_Glow_Right, 60);
    lv_obj_set_x(ui_BTN_Movexy_Glow_Right, 30);
    lv_obj_set_y(ui_BTN_Movexy_Glow_Right, 0);
    lv_obj_set_align(ui_BTN_Movexy_Glow_Right, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BTN_Movexy_Glow_Right, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BTN_Movexy_Glow_Right, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BTN_Movexy_Glow_Right, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTN_Movexy_Glow_Right, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_BTN_Movexy_Glow_Right, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_BTN_Movexy_Glow_Right, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BTN_Movexy_Glow_Right, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BTN_Movexy_Glow_Right, lv_color_hex(0x60BEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BTN_Movexy_Glow_Right, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BTN_Movexy_Glow_Right, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BTN_Movexy_Glow_Right, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_BTN_Movexy_Glow_Right, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_BTN_Movexy_Glow_Right, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_BTN_Movexy_Glow_Right, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Movexy_Top = lv_img_create(ui_BTN_Movexy);
    lv_img_set_src(ui_BTN_Movexy_Top, &ui_img_btn_pad_top_png);
    lv_obj_set_width(ui_BTN_Movexy_Top, LV_SIZE_CONTENT);   /// 242
    lv_obj_set_height(ui_BTN_Movexy_Top, LV_SIZE_CONTENT);    /// 237
    lv_obj_set_align(ui_BTN_Movexy_Top, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTN_Movexy_Top, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTN_Movexy_Top, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BTN_Movexy_Top, 128);

    ui_BTN_Movexy_Label = lv_label_create(ui_BTN_Movexy_Top);
    lv_obj_set_width(ui_BTN_Movexy_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTN_Movexy_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BTN_Movexy_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BTN_Movexy_Label, "Move");
    lv_obj_set_style_text_color(ui_BTN_Movexy_Label, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BTN_Movexy_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BTN_Movexy_Label, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Movexy_Icon_Up = lv_img_create(ui_BTN_Movexy_Top);
    lv_img_set_src(ui_BTN_Movexy_Icon_Up, &ui_img_arrow_up_png);
    lv_obj_set_width(ui_BTN_Movexy_Icon_Up, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_BTN_Movexy_Icon_Up, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_BTN_Movexy_Icon_Up, 0);
    lv_obj_set_y(ui_BTN_Movexy_Icon_Up, -36);
    lv_obj_set_align(ui_BTN_Movexy_Icon_Up, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTN_Movexy_Icon_Up, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTN_Movexy_Icon_Up, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BTN_Movexy_Icon_Up, 128);
    lv_obj_set_style_img_recolor(ui_BTN_Movexy_Icon_Up, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_BTN_Movexy_Icon_Up, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_BTN_Movexy_Icon_Up, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor_opa(ui_BTN_Movexy_Icon_Up, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_BTN_Movexy_Icon_Down = lv_img_create(ui_BTN_Movexy_Top);
    lv_img_set_src(ui_BTN_Movexy_Icon_Down, &ui_img_arrow_down_png);
    lv_obj_set_width(ui_BTN_Movexy_Icon_Down, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_BTN_Movexy_Icon_Down, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_BTN_Movexy_Icon_Down, 0);
    lv_obj_set_y(ui_BTN_Movexy_Icon_Down, 36);
    lv_obj_set_align(ui_BTN_Movexy_Icon_Down, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTN_Movexy_Icon_Down, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTN_Movexy_Icon_Down, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BTN_Movexy_Icon_Down, 128);
    lv_obj_set_style_img_recolor(ui_BTN_Movexy_Icon_Down, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_BTN_Movexy_Icon_Down, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_BTN_Movexy_Icon_Down, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor_opa(ui_BTN_Movexy_Icon_Down, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_BTN_Movexy_Icon_Left = lv_img_create(ui_BTN_Movexy_Top);
    lv_img_set_src(ui_BTN_Movexy_Icon_Left, &ui_img_arrow_left_png);
    lv_obj_set_width(ui_BTN_Movexy_Icon_Left, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_BTN_Movexy_Icon_Left, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_BTN_Movexy_Icon_Left, -36);
    lv_obj_set_y(ui_BTN_Movexy_Icon_Left, 0);
    lv_obj_set_align(ui_BTN_Movexy_Icon_Left, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTN_Movexy_Icon_Left, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTN_Movexy_Icon_Left, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BTN_Movexy_Icon_Left, 128);
    lv_obj_set_style_img_recolor(ui_BTN_Movexy_Icon_Left, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_BTN_Movexy_Icon_Left, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_BTN_Movexy_Icon_Left, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor_opa(ui_BTN_Movexy_Icon_Left, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_BTN_Movexy_Icon_Right = lv_img_create(ui_BTN_Movexy_Top);
    lv_img_set_src(ui_BTN_Movexy_Icon_Right, &ui_img_arrow_right_png);
    lv_obj_set_width(ui_BTN_Movexy_Icon_Right, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_BTN_Movexy_Icon_Right, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_BTN_Movexy_Icon_Right, 36);
    lv_obj_set_y(ui_BTN_Movexy_Icon_Right, 0);
    lv_obj_set_align(ui_BTN_Movexy_Icon_Right, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTN_Movexy_Icon_Right, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTN_Movexy_Icon_Right, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BTN_Movexy_Icon_Right, 128);
    lv_obj_set_style_img_recolor(ui_BTN_Movexy_Icon_Right, lv_color_hex(0xABC1ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_BTN_Movexy_Icon_Right, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_BTN_Movexy_Icon_Right, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor_opa(ui_BTN_Movexy_Icon_Right, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Point_Panel = lv_obj_create(ui_Light);
    lv_obj_set_width(ui_Point_Panel, 100);
    lv_obj_set_height(ui_Point_Panel, 100);
    lv_obj_set_x(ui_Point_Panel, -77);
    lv_obj_set_y(ui_Point_Panel, -28);
    lv_obj_set_align(ui_Point_Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Point_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Point_Panel, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Point_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Point_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Point_Panel, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Point_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Point_Panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Point_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Point = lv_obj_create(ui_Point_Panel);
    lv_obj_set_width(ui_Point, 10);
    lv_obj_set_height(ui_Point, 10);
    lv_obj_set_align(ui_Point, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Point, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTN_Light = lv_img_create(ui_Light);
    lv_img_set_src(ui_BTN_Light, &ui_img_btn_print_down_png);
    lv_obj_set_width(ui_BTN_Light, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_BTN_Light, LV_SIZE_CONTENT);    /// 132
    lv_obj_set_x(ui_BTN_Light, -77);
    lv_obj_set_y(ui_BTN_Light, 66);
    lv_obj_set_align(ui_BTN_Light, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTN_Light, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTN_Light, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BTN_Light, 128);

    ui_BTN_Light_Top = lv_img_create(ui_BTN_Light);
    lv_img_set_src(ui_BTN_Light_Top, &ui_img_btn_print_top_off_png);
    lv_obj_set_width(ui_BTN_Light_Top, LV_SIZE_CONTENT);   /// 105
    lv_obj_set_height(ui_BTN_Light_Top, LV_SIZE_CONTENT);    /// 94
    lv_obj_set_align(ui_BTN_Light_Top, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTN_Light_Top, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE |
                    LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_img_set_zoom(ui_BTN_Light_Top, 128);
    lv_obj_set_style_radius(ui_BTN_Light_Top, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_BTN_Light_Top, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_BTN_Light_Top, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BTN_Light_Top, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_BTN_Light_Top, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_BTN_Light_Top, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BTN_Light_Top, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor(ui_BTN_Light_Top, lv_color_hex(0x67799B), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_BTN_Light_Top, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_BTN_Light_Icon = lv_img_create(ui_BTN_Light_Top);
    lv_img_set_src(ui_BTN_Light_Icon, &ui_img_icn_stop_png);
    lv_obj_set_width(ui_BTN_Light_Icon, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_BTN_Light_Icon, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_align(ui_BTN_Light_Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTN_Light_Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTN_Light_Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BTN_Light_Icon, 128);

    lv_obj_add_event_cb(ui_BTN_Movexy_Glow_Up, ui_event_BTN_Movexy_Glow_Up, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTN_Movexy_Glow_Down, ui_event_BTN_Movexy_Glow_Down, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTN_Movexy_Glow_Left, ui_event_BTN_Movexy_Glow_Left, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTN_Movexy_Glow_Right, ui_event_BTN_Movexy_Glow_Right, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTN_Light_Top, ui_event_BTN_Light_Top, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Light, ui_event_Light, LV_EVENT_ALL, NULL);

}
