// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ee351_ui

#include "../ui.h"

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Settings, &ui_img_bkg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Settings_Header = lv_obj_create(ui_Settings);
    lv_obj_set_width(ui_Settings_Header, 291);
    lv_obj_set_height(ui_Settings_Header, 40);
    lv_obj_set_x(ui_Settings_Header, 0);
    lv_obj_set_y(ui_Settings_Header, -20);
    lv_obj_set_align(ui_Settings_Header, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Settings_Header, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settings_Header, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings_Header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Settings_Header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Settings_Header, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Settings_Header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Settings_Header, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Settings_Header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Settings_Header_Label = lv_label_create(ui_Settings_Header);
    lv_obj_set_width(ui_Settings_Header_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Settings_Header_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Settings_Header_Label, 0);
    lv_obj_set_y(ui_Settings_Header_Label, 10);
    lv_obj_set_align(ui_Settings_Header_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Settings_Header_Label, "Settings");
    lv_obj_set_style_text_color(ui_Settings_Header_Label, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Settings_Header_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Settings_Header_Label, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Settings, ui_event_Settings, LV_EVENT_ALL, NULL);

}
