// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ee351_ui

#ifndef _EE351_UI_UI_H
#define _EE351_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Home
void ui_Home_screen_init(void);
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_BTN_Test;
extern lv_obj_t * ui_Test_Top;
extern lv_obj_t * ui_Test_Top_Icon;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_bkg_png);    // assets\bkg.png
LV_IMG_DECLARE(ui_img_btn_print_down_png);    // assets\btn_print_down.png
LV_IMG_DECLARE(ui_img_btn_print_top_off_png);    // assets\btn_print_top_off.png
LV_IMG_DECLARE(ui_img_icn_stop_png);    // assets\icn_stop.png
LV_IMG_DECLARE(ui_img_icn_time_1_png);    // assets\icn_time_1.png
LV_IMG_DECLARE(ui_img_icn_time_2_png);    // assets\icn_time_2.png

LV_FONT_DECLARE(ui_font_Small_Font);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
